### ISSUE TITLE
Node 18 error

### ISSUE THREAD

**Issue by stefanotauriello** [jeremydaly/data-api-client#131]
Hello,
in Lambda from NodeJS v14 to v18, how have I to rewrite it?
Is there something else?

const data = require('data-api-client')({
secretArn: 'xxxx',
resourceArn: 'yyy',
database: 'zzz',
engine: 'pg'
});

**Comment by stefanotauriello** [comment]
Resolved!

**Comment by jeremydaly** [comment]
I'm glad you figured this out!

**Comment by stefanotauriello** [comment]
Thank you!
Every obstacle is an opportunity 😎


Il giorno mer 11 ott 2023 alle 14:09 Jeremy Daly ***@***.***>
ha scritto:
