### ISSUE TITLE
Oracle Cursor Expressions Like on MySql ?

### ISSUE THREAD

**Issue by CarlosValenca** [jeremydaly/data-api-client#24]
Hello Jeremy, How are you doing ?

Do you know if in this API exist some resource or alternative to query something like we do on Oracle Cursor Expressions in order to receive a result as a sub level on JSON ? (there we do something like this select 1, 2, 3, cursor(select 4,5,6 from dual) from dual and then we have a set with a subset of records).
As I'm using MySql Aurora Serverless and the current version does not have JSON features already present on other versions for MySql I was wondering if something like that already exists in the API.
If not, would you possibly recommend something ?

Thank You in Advance !

Carlos

**Comment by jeremydaly** [comment]
Hi Carlos,

Thanks for this. I just released an update version of the library, but I don't believe the current version of Aurora Serverless MySQL supports this. I will continue to do more research, but please feel free to add any more context.

Thanks,
Jeremy
