### ISSUE TITLE
Parameterize identifiers: order by

### ISSUE THREAD

**Issue by stevehogdahl** [jeremydaly/data-api-client#25]
I'm trying to run the following query for dynamic sorting. 

```
SELECT * FROM tenant ORDER BY ::column DESC
{ column: 'industry' }
```

I get the following error though.
```
BadRequestException: ERROR: operator does not exist: ` character varying
Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

**Comment by stevehogdahl** [comment]
I found out this is because the underlying sqlstring module escapes these identifiers as \`column\` and postgres does not support this.

**Comment by jeremydaly** [comment]
This wasn't designed to support the PostgreSQL version (didn't exist at that time), but I suppose it could. Is this the only issue you see between the two?

**Comment by stevehogdahl** [comment]
Another issue i found was enum columns. Postgres threw a data type error. I don't have much more information on this because i just concated the value to the query and moved on.
