### ISSUE TITLE
Retrieval of out params for stored procedures

### ISSUE THREAD

**Issue by ChrisTurvil** [jeremydaly/data-api-client#29]
Just wondering if there is any way to get at out params from stored procedure calls?

My INSERT is unfortunately hidden in a sproc - sp_create_thingy(blah, out newId). In the standard node MySQL client it's clunky but you can pass something like this "CALL sp_create_thingy(blah, @foo); select @foo;" (as long as the multiple-statements option is turned on). 

I'm not sure how to achieve a similar effect with this library? Is this possible?

**Comment by jeremydaly** [comment]
This is likely a limitation of the Data API, not the library. Multiple statements are not allowed for obvious security reasons.

Did you try running it in a transaction? With two separate queries?

**Comment by ChrisTurvil** [comment]
Thanks Jeremy - and thanks for the great module! I did try a transaction but I wasn't sure (given the underlying https calls) whether LAST_INSERT_ID() would be entirely safe. There does seem to be some persistence between calls on the same connection as tested by setting things like SQL_SAFE_UPDATES across multiple calls - which worked even outside of a transaction. All things considered though I'm going to play safe and update the sprocs to return a result set with the new ID instead of out params. Thanks again :)
