### ISSUE TITLE
column [column name] is of type jsonb but expression is of type character varying

### ISSUE THREAD

**Issue by naveennazimudeen** [jeremydaly/data-api-client#34]
In Postgres, an insert that has jsonb data type gives the error:
`column [column name] is of type jsonb but expression is of type character varying`

**Comment by naveennazimudeen** [comment]
I got it to work based on the input on this thread: https://forums.aws.amazon.com/thread.jspa?messageID=921843&#921843

`'INSERT into post."post" (content, created_by) values (:content::jsonb, :created_by::uuid) returning post_uuid', 
      {
        content: JSON.stringify({web: {...post}}),
        created_by
      }`

**Comment by jeremydaly** [comment]
Thanks for the note. This library has a conflict with some PostgreSQL features, so I'm in the process of fixing that.

**Comment by MarkHerhold** [comment]
I also am hitting the same issue with enums in PG. This lib assumes enums are a string, even with casting (`::enum`). 

```
parameters: [
  { name: 'column', value: { stringValue: '<some enum value>' } }
]
```

**Comment by jeremydaly** [comment]
Closing this in favor of #27
