### ISSUE TITLE
Issues with aws-sdk version

### ISSUE THREAD

**Issue by matuella** [jeremydaly/data-api-client#4]
AWS Lambda Runtimes provide by default the `aws-sdk` in the AWS environment, so it's only necessary to npm install it in the **devDependencies**.

Assuming this scenario - where we use the aws-sdk provided by the AWS environment - the following occurs when running with node **8.10 runtime**:
```
module initialization error: TypeError
at module.exports (/var/task/node_modules/data-api-client/index.js:464:10)
at Object.<anonymous> (/var/task/testJS.js:5:17)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
```

which is [this line here](https://github.com/jeremydaly/data-api-client/blob/b78ce51e407db98ad82dc764e4cfe13ab967ae19/index.js#L464) - that accesses the `RDSDataService`.

And when we run in the **10.x runtime**, a more specific error is shown ([tested based on this issue](https://github.com/jeremydaly/data-api-client/issues/3)):

```JSON
{
    "errorType": "TypeError",
    "errorMessage": "config.RDS.executeStatement is not a function",
    "stack": [
        "TypeError: config.RDS.executeStatement is not a function",
        "    at query (/var/task/node_modules/data-api-client/index.js:321:22)",
        "    at Object.query (/var/task/node_modules/data-api-client/index.js:471:22)",
        "    at Runtime.module.exports.main [as handler] (/var/task/testJS.js:21:34)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:63:25)",
        "    at process._tickCallback (internal/process/next_tick.js:68:7)"
    ]
}
```

-----

My guess is that this is due to the fact that [AWS provides the following versions in the respective runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html):
> Name | Identifier | Node.js Version | AWS SDK for JavaScript | Operating System
> -- | -- | -- | -- | --
> Node.js 10 | nodejs10.x | 10.15 | **2.437.0** | Amazon Linux 2
> Node.js 8.10 | nodejs8.10 | 8.10 | **2.290.0** | Amazon Linux

If we analyze the [aws-sdk changelog](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md), the errors make sense now. Probably because the `2.290.0` does not include `RDSDataService` at all, and `2.437.0` does not have `executeStatement` (https://github.com/jeremydaly/data-api-client/issues/3) (released in `2.466.0`.

My question is: is there a way to change the version of the aws-sdk (the one that's default in each runtime)? Or we have to package it with our lambdas - thus increasing the size of the package?

Nonetheless, I suggest updating the README with this information (if agreed, I'm up to contributing on this particular issue).

**Comment by pipeu** [comment]
Hi,

This error "**AWS.RDSDataService is not a constructor**" happened with me too.

I did a small test importing data-api-client main function (index.js) into my project using aws-sdk 2.480.0 and it worked very well.

**Comment by matuella** [comment]
@pipeu Yeah, this problem can be solved by directly importing the aws-sdk versions superior to `2.466.0`. But in my perspective, that's a workaround for this lib, given the nature of AWS Lambdas providing the aws-sdk in its runtime.
