### ISSUE TITLE
Needed some tuning for the policies

### ISSUE THREAD

**Issue by yassineim** [jeremydaly/data-api-client#41]
I'm not sure why but this
`"Resource": "arn:aws:secretsmanager:{REGION}:{ACCOUNT-ID}:secret:{PATH-TO-SECRET}/*"` didn't work while this
`"Resource": "arn:aws:secretsmanager:{REGION}:{ACCOUNT-ID}:secret:{PATH-TO-SECRET}"` did (no slash + asterisk at the end).

**Comment by jeremydaly** [comment]
I'm not having any issues with these settings. What region are you in?

**Comment by jaska120** [comment]
I had the same issue and the solution proposed by yassineim fixed the issue.

I am on `eu-west-1` region.

**Comment by ffxsam** [comment]
@yassineim @jaska120

See this article on AWS: https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonrdsdataapi.html#amazonrdsdataapi-resources-for-iam-policies

The official recommendation is to use `"Resource": "*"`. Yes, this goes against the concept of least privileged access, but it's what Amazon said to do.

More [details here](https://github.com/jeremydaly/data-api-client/issues/64#issuecomment-718193356).
