### ISSUE TITLE
Unable to make queries that don't depend on a database

### ISSUE THREAD

**Issue by srchulo** [jeremydaly/data-api-client#47]
If I want to run a query like:

`SHOW DATABASES`

I get this error:

`"errorMessage": "No 'database' provided."`

Even though I'm able to run a command like this on no database and get results:

`aws rds-data execute-statement --resource-arn $resourceArn --secret-arn $secretArn --sql "SHOW DATABASES"`

Would it be possible to allow queries that aren't tied to a specific database?

**Comment by jeremydaly** [comment]
All set. Will be pushed in the next release.

**Comment by srchulo** [comment]
Awesome, thanks! :)
