### ISSUE TITLE
How to handle null / undefined values when inserting / updating data rows?

### ISSUE THREAD

**Issue by the-smart-home-maker** [jeremydaly/data-api-client#50]
Dear data-api-client supporters,

I have a simple question: How to handle null / undefined values when inserting / updating data rows? No matter if I leave parameters as `undefined` or explicitly set them as `null`, I always receive an error message either saying `'field_x' is an invalid type` (when passing the parameter as `undefined`) or `Unknown column 'field_x' in 'field list'` (when passing the parameter as `null`). How can I explicitly set a field as `NULL` in the database?

Thanks a lot and best regards
The Smart Home Maker

**Comment by the-smart-home-maker** [comment]
I got it working - was a problem with my setup so we can close this issue

**Comment by martinpllu** [comment]
Hi @the-smart-home-maker, I'm facing the same issue - can I ask how you resolved it please?

**Comment by the-smart-home-maker** [comment]
> Hi @the-smart-home-maker, I'm facing the same issue - can I ask how you resolved it please?

Hi @martinpllu,

I figured you need to make sure to explicitly set missing values to null, not undefined.
That should do the trick.

**Comment by martinpllu** [comment]
Thanks @the-smart-home-maker <https://github.com/the-smart-home-maker>,
much appreciated!
