### ISSUE TITLE
Is connection takes long time 

### ISSUE THREAD

**Issue by rabimatuag** [jeremydaly/data-api-client#99]
when I do db.query it takes long time at first (don't know just predicted )and after that hit it gives result within short time
and after some gap if again the db.query triggered then it takes some time as previous why?

**Comment by ffxsam** [comment]
Most likely nothing to do with this library. Are you using Aurora Serverless? It sounds like maybe you have auto-pause enabled, and the database is spun down. So your first query spins it up (can take 20 seconds or so), then the subsequent queries are faster.

**Comment by rabimatuag** [comment]
Thank you for the information. Yeah I have used aurora Serverless .So, not to spun down I need to disable autoPase  providing duration 0 yeah

**Comment by rabimatuag** [comment]
not an issue
